---
title: Grow a tree
hero_image: images/selfie.png
description: Stay as still as you can to grow a tree using a computer's camera to
  detect any movement
version: 7
listed: true
copyedit: true
last_tested: '2020-09-01'
steps:
- title: Introduction
- title: How still can you be?
  completion:
  - engaged
- title: 'Challenge: change conditions'
  completion:
  - internal
- title: What next?
  completion:
  - external
