title: Grow a tree
hero_image: images/selfie.png
description: Stay as still as you can to grow a tree using a computer's camera to detect any movement
version: 7
listed: false
copyedit: false
last_tested: "2020-05-18"
steps:
  - title: Introduction
  - title: How still can you be?
  - title: 'Challenge: changing conditions'
  - title: What next?
